# Generated by Django 4.2.3 on 2023-07-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos')),
            ],
        ),
        migrations.RemoveField(
            model_name='libro',
            name='foto',
        ),
    ]
