# Generated by Django 4.2.3 on 2023-07-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_imagen_remove_libro_foto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imagen',
        ),
        migrations.AddField(
            model_name='libro',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos'),
        ),
    ]
