# Generated by Django 4.2.3 on 2023-07-15 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_libro_precio'),
        ('inicio', '0003_delete_imagen_libro_foto'),
    ]

    operations = [
    ]
