# Generated by Django 4.2.3 on 2023-07-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_merge_0002_libro_precio_0003_delete_imagen_libro_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='foto',
        ),
        migrations.AddField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='libros/'),
        ),
    ]
