# Generated by Django 4.2.3 on 2023-07-15 22:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inicio', '0007_alter_libro_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='generacion',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 1, 1, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libro',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
