# Generated by Django 4.2.3 on 2023-07-15 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0008_libro_generacion_libro_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='generacion',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='libro',
            old_name='user',
            new_name='propietario',
        ),
    ]
